import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";

export default {
  input: "src/transcribe.mjs",
  output: {
    file: "package/lib/transcribe.mjs",
    format: "es",
  },
  plugins: [
    resolve({ preferBuiltins: true }),
    commonjs(),
    json(),
  ],
  external: [
    "node:fs",
    "node:path",
    "node:os",
    "node:child_process",
    "node:http",
    "node:https",
    "node:stream",
    "node:buffer",
    "node:url",
    "node:util",
    "node:events",
    "node:net",
    "node:tls",
    "node:zlib",
    "node:crypto",
    "node:worker_threads",
    "node:async_hooks",
    "node:diagnostics_channel",
    "node:string_decoder",
    "fs",
    "path",
    "os",
    "child_process",
    "http",
    "https",
    "stream",
    "buffer",
    "url",
    "util",
    "events",
    "net",
    "tls",
    "zlib",
    "crypto",
    "worker_threads",
    "async_hooks",
    "diagnostics_channel",
    "string_decoder",
  ],
};
